-- ============================================================
-- Rangers デモ用シードデータ（検証網羅版）
-- ============================================================
-- 実行手順（2ステップ）:
--
--   Step 1: ユーザー作成（Admin API 経由 / 初回のみ）
--     node supabase/seed_users.mjs
--
--   Step 2: チーム・セッションデータ投入
--     npx supabase db query --linked --file supabase/seed_data.sql
--
-- テストアカウント（全パスワード: test1234）:
--   test1@example.com → 山田 健太 ★チーム管理者
--   test2@example.com → 鈴木 太郎（レギュラー会員）
--   test3@example.com → 佐藤 花子（回数券会員・スタンプ残7回）
--   test4@example.com → 田中 新太郎（新規・チーム未所属）
--
-- 注意:
--   GoTrue v2 以降は auth.users への直接 INSERT を使うと
--   signInWithPassword が "Database error querying schema" で失敗します。
--   必ず Admin API（seed_users.mjs）経由でユーザーを作成してください。
-- ============================================================
